const courseData = [
  {
    week: "SEMANA 14",
    title: "Patología ambiental. Enfermedades nutricionales.",
    items: [
      { type: "book", title: "TRICROMICA ESTEATOHEPATITIS", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=30ac7c2a", definicion: ["La esteatohepatitis tricrómica es una forma de enfermedad hepática caracterizada por la inflamación del hígado y la acumulación de grasa en las células hepáticas.", "Se asocia con la esteatosis hepática no alcohólica (EHNA) y puede progresar a cirrosis y otros trastornos hepáticos graves.", "La esteatohepatitis tricrómica se caracteriza por la presencia de tres tipos de células: hepatocitos con gotas de grasa, células inflamatorias y células de Mallory-Denk."], caracteristicas: ["La presencia de gotas de grasa en los hepatocitos, que pueden ser microvesiculares o macrovesiculares.", "Inflamación lobular con infiltración de células inflamatorias, como linfocitos y macrófagos.", "La presencia de células de Mallory-Denk, que son hepatocitos con alteraciones citoplasmáticas y núcleo irregular.", "Fibrosis pericelular y perivenular, que puede progresar a cirrosis en etapas avanzadas de la enfermedad."] },
      { type: "book", title: "ATROFIA MUSCULAR", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=0944089e", definicion: ["La atrofia muscular es la disminución del tamaño y la masa muscular debido a la pérdida de fibras musculares o a la reducción del diámetro de estas", "Puede ser causada por diversas condiciones, como lesiones, enfermedades neuromusculares, desuso o denervación", "Se caracteriza por una disminución de la fuerza muscular y una reducción de la función motora"], caracteristicas: ["Reducción del diámetro de las fibras musculares", "Disminución del número de fibras musculares", "Aumento de la cantidad de tejido conectivo en el músculo", "Presencia de cambios degenerativos en las fibras musculares, como la fragmentación y la necrosis"] },
      { type: "book", title: "STEATONECROSIS", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=6e72fe88", definicion: ["La esteatonecrosis es una lesión hepática caracterizada por la acumulación de grasa y necrosis celular", "Se asocia con diversas condiciones, como la obesidad, el alcoholismo y el uso de ciertos medicamentos", "Puede ser un hallazgo incidental en biopsias hepáticas o estar relacionada con enfermedades hepáticas más graves"], caracteristicas: ["Acumulación de gotas de grasa en los hepatocitos, que puede ser microvesicular o macrovesicular", "Necrosis celular, que puede ser apoptótica o necrótica", "Inflamación leve a moderada, con presencia de células inflamatorias como neutrófilos y linfocitos", "Fibrosis pericelular, que puede ser una respuesta a la lesión hepática crónica"] },
      { type: "book", title: "ESTEATOHEPATITIS RETICULINA", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=35193038", definicion: ["La esteatohepatitis reticulina es una condición hepática caracterizada por la inflamación y el daño en el hígado debido a la acumulación de grasa", "Se considera una forma de enfermedad hepática no alcohólica (EHNA) y puede progresar a cirrosis o cáncer de hígado si no se trata", "La esteatohepatitis reticulina puede ser causada por una combinación de factores, incluyendo la obesidad, la diabetes tipo 2 y la resistencia a la insulina"], caracteristicas: ["La presencia de gotas de grasa en las células hepáticas (esteatosis) es una característica microscópica clave de la esteatohepatitis reticulina", "La inflamación en el hígado, que puede incluir la presencia de células inflamatorias como los linfocitos y los macrófagos", "La necrosis de las células hepáticas, que puede ser evidente en la forma de cuerpos de Councilman o de apoptosis", "La fibrosis, que es la formación de tejido cicatricial en el hígado, puede ser una característica microscópica en etapas más avanzadas de la enfermedad"] },
      { type: "book", title: "ESTEATOHEPATITIS HE", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=a276d6a3", definicion: ["La esteatohepatitis es una inflamación del hígado causada por la acumulación de grasa en las células hepáticas", "Se caracteriza por la presencia de inflamación y daño hepático, además de la esteatosis", "Es una forma de enfermedad hepática no alcohólica que puede progresar a cirrosis y cáncer de hígado"], caracteristicas: ["Presencia de gotas de grasa en las células hepáticas (esteatosis)", "Inflamación del tejido hepático con presencia de células inflamatorias", "Daño a las células hepáticas con presencia de necrosis y apoptosis", "Fibrosis hepática, que puede progresar a cirrosis en etapas avanzadas"] },
      { type: "book", title: "ESTEATOSIS HEPATICA", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=851c76fc", definicion: ["La esteatosis hepática se refiere a la acumulación anormal de grasa en las células del hígado", "Esta condición puede ser causada por una variedad de factores, incluyendo el consumo excesivo de alcohol, la obesidad y la diabetes", "La esteatosis hepática puede ser asintomática, pero en algunos casos puede progresar a enfermedades hepáticas más graves"], caracteristicas: ["La presencia de gotas de grasa en las células hepáticas, que pueden ser visualizadas mediante microscopía", "La inflamación y la necrosis de las células hepáticas, que pueden ser indicativas de una progresión a enfermedades más graves", "La formación de fibrosis, que es la deposición de tejido cicatricial en el hígado", "La alteración de la arquitectura hepática normal, con la presencia de nódulos y la distorsión de los lobulillos hepáticos"] }
    ]
  },
  {
    week: "SEMANA 13",
    title: "Infecciones micóticas y parasitarias.",
    items: [
      { type: "book", title: "SEMANA 13: INFECCIONES MICÓTICAS Y PARASITARIAS", date: "Publicado: 2 abr 2023" },
      { type: "book", title: "LEISHMANIASIS 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=30b02492", definicion: ["La leishmaniasis es una enfermedad infecciosa causada por parásitos del género Leishmania", "Se transmite a través de la picadura de un mosquito infectado del género Phlebotomus", "Puede presentarse en diferentes formas clínicas, como cutánea, mucocutánea o visceral"], caracteristicas: ["Los parásitos Leishmania se encuentran dentro de los macrófagos del huésped", "Presentan un flagelo largo y delgado en la forma promastigota", "En la forma amastigota, carecen de flagelo y tienen un núcleo grande y redondo", "Se pueden observar en frotis de tejido o sangre teñidos con Giemsa o Wright"] },
      { type: "book", title: "STRONGYLOIDIASIS", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=4797eadf", definicion: ["La strongyloidiasis es una infección parasitaria causada por el nematodo Strongyloides stercoralis", "Se caracteriza por la invasión de los parásitos en el intestino delgado y la piel", "Puede causar una variedad de síntomas, desde asintomáticos hasta enfermedad grave y potencialmente mortal"], caracteristicas: ["Los huevos de Strongyloides stercoralis son ovalados y tienen una longitud de aproximadamente 50-60 micrómetros", "Las larvas rhabditiformes tienen una longitud de aproximadamente 200-300 micrómetros y un diámetro de 10-15 micrómetros", "Las larvas filariformes son más largas y delgadas que las rhabditiformes, con una longitud de aproximadamente 500-700 micrómetros", "Los parásitos adultos tienen una longitud de aproximadamente 1-2 centímetros y un diámetro de 0,5-1 milímetro"] },
      { type: "book", title: "NEUMONIA EOSINOFILICA", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=67b375df", definicion: ["La neumonía eosinofílica es una condición inflamatoria del pulmón caracterizada por la infiltración de eosinófilos en el tejido pulmonar", "Se asocia con una variedad de causas, incluyendo infecciones parasitarias, reacciones a medicamentos y enfermedades autoinmunes", "Puede presentarse con síntomas como tos, fiebre, dolor en el pecho y dificultad para respirar"], caracteristicas: ["Infiltración de eosinófilos en el intersticio pulmonar y en los alvéolos", "Presencia de células gigantes y células de Langhans en algunas formas de la enfermedad", "Edema y congestión de los capilares pulmonares", "Fibrosis intersticial en etapas avanzadas de la enfermedad"] },
      { type: "book", title: "CISTICERCOSIS", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=ac251936", definicion: ["La cisticercosis es una enfermedad parasitaria causada por el estadio larvario del gusano cestodo Taenia solium", "Se caracteriza por la formación de quistes en diferentes tejidos del cuerpo, incluyendo el cerebro, músculos y otros órganos", "La infección se produce mediante la ingestión de huevos del parásito, que pueden estar presentes en alimentos o agua contaminados"], caracteristicas: ["Los quistes de cisticercosis tienen una pared fibrosa y contienen un líquido claro con el escólex del parásito", "Microscópicamente, se observa una estructura característica con una pared de tres capas: una capa externa fibrosa, una capa media de tejido conectivo y una capa interna de epitelio", "El escólex del parásito presenta cuatro ventosas y un rostellum con ganchos, que se utilizan para la fijación y la nutrición", "La respuesta inflamatoria del huésped puede variar desde una reacción mínima hasta una respuesta intensa con necrosis y fibrosis"] },
      { type: "book", title: "CROMOMICOSIS", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=4b0573b6", definicion: ["La cromomicosis es una infección fúngica crónica que afecta la piel y los tejidos subcutáneos", "Se caracteriza por la formación de nódulos o úlceras en la piel, que pueden ser dolorosas y supurar", "La cromomicosis es causada por hongos como Fonsecaea, Phialophora y Cladophialophora, que se encuentran comúnmente en el suelo y la vegetación"], caracteristicas: ["La cromomicosis se caracteriza por la presencia de escleritos, que son estructuras fúngicas compactas y oscuras que se encuentran en los tejidos infectados", "En el examen microscópico, se pueden observar hifas y escleritos de los hongos causantes, que pueden estar rodeados de inflamación y necrosis", "La infección puede causar una respuesta inflamatoria intensa, con la presencia de células gigantes y células epitelioides", "La cromomicosis puede ser difícil de tratar, ya que los hongos causantes pueden ser resistentes a los tratamientos antifúngicos convencionales"] },
      { type: "book", title: "ASPERGILOSIS", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=578bfaa7", definicion: ["La aspergilosis es una infección causada por el hongo Aspergillus", "Puede afectar a personas con sistemas inmunitarios debilitados", "Se presenta en diferentes formas, como aspergilosis pulmonar, cutánea o sistémica"], caracteristicas: ["Hifas ramificadas en ángulo de 45 grados", "Conidios esféricos o elipsoidales", "Colonias verdes o azules en agar", "Estructuras de fructificación en forma de cabezuelas"] },
      { type: "book", title: "TORULOSIS 1", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=fb8beef1", definicion: ["La torulosis es una infección fúngica causada por el hongo Cryptococcus neoformans", "Se caracteriza por la presencia de lesiones en el sistema nervioso central y otros órganos", "Es más común en personas con sistemas inmunitarios debilitados, como aquellos con VIH/SIDA"], caracteristicas: ["El hongo Cryptococcus neoformans se presenta como una levadura con cápsula gelatinosa", "La cápsula es visible con tinción de India y se utiliza para el diagnóstico", "Las células fúngicas pueden aparecer solas o en pares, y a menudo se encuentran dentro de macrófagos", "La infección puede causar inflamación y necrosis en los tejidos afectados, lo que puede llevar a la formación de granulomas"] },
      { type: "book", title: "QUISTE HIDATIDICO", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=cb81c0fe", definicion: ["El quiste hidatídico es una lesión parasitaria causada por la larva de la tenia Echinococcus", "Se caracteriza por la formación de quistes llenos de líquido en órganos como el hígado, pulmones o riñones", "Es una enfermedad zoonótica, es decir, se transmite entre animales y humanos"], caracteristicas: ["El quiste hidatídico tiene una pared fibrosa y una membrana germinal interna que produce los escólex", "La membrana germinal produce brotes que se proyectan hacia el interior del quiste, formando vesículas filleas", "El contenido del quiste es un líquido claro y estéril, con una presión interna que puede causar síntomas", "En el microscopio, se observan los escólex y las vesículas filleas, que son características del quiste hidatídico"] },
      { type: "book", title: "TORULOSIS 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=f8ff345d", definicion: ["La torulosis es una infección fúngica causada por el hongo Cryptococcus neoformans", "Se caracteriza por la presencia de lesiones en el sistema nervioso central y otros órganos", "Es más común en personas con sistemas inmunitarios debilitados, como aquellos con VIH/SIDA"], caracteristicas: ["El hongo Cryptococcus neoformans se presenta en forma de levadura, con una cápsula gelatinosa", "La cápsula es visible con tinción de India y se utiliza para el diagnóstico", "Las células fúngicas pueden aparecer solas o en parejas, y a menudo se encuentran en el líquido cefalorraquídeo", "La infección puede causar inflamación y daño en los tejidos infectados, lo que puede llevar a síntomas graves"] }
    ]
  },
  {
    week: "SEMANA 12",
    title: "Infecciones virales y bacterianas.",
    items: [
      { type: "video", title: "VIDEO LEPRA", date: "Editado: 29 may 2023" },
      { type: "book", title: "TUBERCULOSIS MILIAR 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=f6d877b0", definicion: ["La tuberculosis miliar es una forma de tuberculosis que se caracteriza por la diseminación de la infección a través de la sangre", "Se produce cuando la bacteria Mycobacterium tuberculosis se dispersa a través del torrente sanguíneo y afecta múltiples órganos", "Es una forma grave y potencialmente mortal de la enfermedad, especialmente si no se trata adecuadamente"], caracteristicas: ["La presencia de granulomas miliarios en los órganos afectados, que son pequeños focos de inflamación que contienen la bacteria", "La observación de bacilos ácido-alcohol resistentes en las muestras de tejido o líquido corporal", "La presencia de necrosis caseosa en los granulomas, que es un tipo de necrosis característica de la tuberculosis", "La infiltración de células inflamatorias, como macrófagos y linfocitos, en los tejidos afectados"] },
      { type: "book", title: "MENINGITIS PURULENTA", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=dce3bcc4", definicion: ["Inflamación del tejido meníngeo que rodea el cerebro y la médula espinal", "Causada por infecciones bacterianas, virales o fúngicas", "Se caracteriza por la presencia de pus en el líquido cefalorraquídeo"], caracteristicas: ["Presencia de neutrófilos y monocitos en el líquido cefalorraquídeo", "Aumento de la proteína y la glucosa en el líquido cefalorraquídeo", "Visualización de bacterias como Neisseria meningitidis, Streptococcus pneumoniae o Haemophilus influenzae", "Inflamación y edema del tejido meníngeo con posible necrosis"] },
      { type: "book", title: "NEUMONIA", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=363eae18", definicion: ["La neumonía es una inflamación del tejido pulmonar, generalmente causada por infecciones bacterianas, virales o fúngicas.", "Se caracteriza por la presencia de síntomas respiratorios como tos, fiebre, dolor en el pecho y dificultad para respirar.", "Puede afectar a personas de cualquier edad, aunque es más común y grave en niños pequeños, adultos mayores y personas con sistemas inmunitarios debilitados."], caracteristicas: ["La neumonía puede presentar infiltrados pulmonares en la radiografía de tórax, que son áreas opacas que indican la presencia de líquido o tejido inflamado en los pulmones.", "Microscópicamente, se observa la presencia de neutrófilos y macrófagos en el tejido pulmonar, lo que indica una respuesta inflamatoria.", "La presencia de exudado purulento en los alvéolos pulmonares es característica de la neumonía bacteriana.", "En algunos casos, se pueden observar cambios fibrosos y cicatriciales en el tejido pulmonar, especialmente en neumonías crónicas o recurrentes."] },
      { type: "book", title: "lepra lepromatosa 1", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=f41578e5", definicion: ["La lepra lepromatosa es una forma grave y contagiosa de la enfermedad de Hansen", "Se caracteriza por una infección crónica y progresiva que afecta principalmente la piel y los nervios periféricos", "La lepra lepromatosa es causada por la bacteria Mycobacterium leprae y se transmite a través del contacto cercano con una persona infectada"], caracteristicas: ["La presencia de bacilos ácido-alcohol resistentes en grandes cantidades en las lesiones cutáneas y en los tejidos linfoides", "Infiltración difusa de células inflamatorias, como histiocitos y linfocitos, en la dermis", "Degeneración de los nervios periféricos, lo que puede llevar a pérdida de sensibilidad y función motora", "Formación de granulomas en los tejidos afectados, que pueden ser diagnosticados mediante biopsia"] },
      { type: "book", title: "lepra lepromatosa 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=a36dc360", definicion: ["La lepra lepromatosa es una forma grave y contagiosa de la enfermedad de Hansen", "Se caracteriza por una infección crónica y progresiva que afecta principalmente la piel y los nervios periféricos", "La lepra lepromatosa es causada por la bacteria Mycobacterium leprae y se transmite a través del contacto cercano con una persona infectada"], caracteristicas: ["Infiltración difusa de células inflamatorias en la dermis, con predominio de histiocitos y linfocitos", "Presencia de granulomas lepromatosos, que son agregados de células inflamatorias que contienen bacterias", "Degeneración de los nervios periféricos, con pérdida de la mielina y la axona", "Aparición de cuerpos de Virchow, que son agregados de bacterias dentro de los histiocitos"] },
      { type: "book", title: "COLORACION DE FITE", date: "Publicado: 28 may 2023" },
      { type: "book", title: "ACTINOMICES", date: "Editado: 21 jun 2023" },
      { type: "book", title: "ACTINOMICES", date: "Publicado: 27 may 2023" }
    ]
  },
  {
    week: "SEMANA 11",
    title: "Neoplasias mesenquimales y linfoides.",
    items: [
      { type: "video", title: "VIDEO TUMOR DE LAS GIGANTES MULTINUCLEADAS", date: "Publicado: 27 may 2023" },
      { type: "video", title: "VIDEO RABDOMIOMA ADULTO", date: "Publicado: 27 may 2023, 2 comentarios", url: "https://pathpresenter.net/public/display?token=55d5b56f", definicion: ["Tumor benigno de músculo esquelético que se presenta en adultos", "Se caracteriza por un crecimiento lento y no invasivo", "Puede ocurrir en cualquier parte del cuerpo, pero es más común en la cabeza y el cuello"], caracteristicas: ["Está compuesto por células musculares maduras con núcleos periféricos", "Presenta una arquitectura fascicular o en mosaico", "Las células tumorales pueden tener un tamaño variable y pueden mostrar vacuolización citoplasmática", "Puede haber áreas de degeneración y fibrosis en el tumor"] },
      { type: "video", title: "video de linfoma difuso de celulas b grande", date: "Publicado: 26 may 2023" },
      { type: "video", title: "video linfoma de Hodgkin esclerosis nodular", date: "Publicado: 26 may 2023", url: "https://pathpresenter.net/public/display?token=2e61c3f7", definicion: ["El linfoma de Hodgkin es un tipo de cáncer que afecta el sistema linfático", "La esclerosis nodular es un subtipo de linfoma de Hodgkin caracterizado por la formación de nódulos de tejido fibroso", "Se presenta con mayor frecuencia en adultos jóvenes y tiene un pronóstico generalmente favorable con tratamiento"], caracteristicas: ["Presencia de células de Reed-Sternberg, que son células anormales grandes y binucleadas", "Infiltración de células inflamatorias como linfocitos, eosinófilos y histiocitos en el tejido linfático", "Formación de nódulos de tejido fibroso que rodean a las células neoplásicas", "Arquitectura nodular con áreas de esclerosis fibrosa que pueden rodear a los nódulos tumorales"] },
      { type: "video", title: "VIDEO OSTEOSARCOMA", date: "Publicado: 25 may 2023", url: "https://pathpresenter.net/public/display?token=a4ebb307", definicion: ["Es un tipo de cáncer que se origina en los huesos", "Se caracteriza por la producción de matriz ósea anormal por parte de las células cancerosas", "Es el tipo más común de sarcoma óseo y puede ocurrir en cualquier hueso, pero es más frecuente en los huesos largos de las extremidades"], caracteristicas: ["Células tumorales con núcleos pleomórficos y anisocariosis", "Producción de matriz ósea anormal, que puede ser osteoide, condroide o fibroide", "Presencia de células gigantes y mitosis atípicas", "Invasión destructiva del hueso circundante y posible extensión a los tejidos blandos adyacentes"] },
      { type: "book", title: "OSTEOSARCOMA 2", date: "Publicado: 22 may 2023", url: "https://pathpresenter.net/public/display?token=a4ebb307", definicion: ["Es un tipo de cáncer que se origina en los osteoblastos, las células que producen el tejido óseo", "Se caracteriza por la producción de matriz ósea anormal por parte de las células tumorales", "Es el tipo más común de sarcoma óseo y puede ocurrir en cualquier edad, pero es más frecuente en adolescentes y adultos jóvenes"], caracteristicas: ["Presenta células tumorales con núcleos pleomórficos y anisocariosis, con áreas de necrosis y hemorragia", "Se observan trabéculas óseas anormales y desorganizadas, con osteoides producidos por las células tumorales", "Puede haber áreas de cartilago y tejido fibroso dentro del tumor", "La inmunohistoquímica puede mostrar positividad para marcadores como vimentina, osteocalcina y osteopontina"] },
      { type: "book", title: "OSTEOSARCOMA", date: "Publicado: 22 may 2023", url: "https://pathpresenter.net/public/display?token=a4ebb307", definicion: ["Es un tipo de cáncer que se origina en los osteoblastos, las células que producen el tejido óseo", "Se caracteriza por la producción de matriz ósea anormal por parte de las células tumorales", "Es el tipo más común de sarcoma óseo y puede afectar a personas de cualquier edad, aunque es más frecuente en adolescentes y adultos jóvenes"], caracteristicas: ["Presenta células tumorales con núcleos pleomórficos y anisocariosis, lo que indica un alto grado de anaplasia", "Se observan áreas de necrosis y hemorragia dentro del tumor", "La producción de matriz ósea anormal puede ser osteoide, condroide o fibroide", "Puede mostrar invasión a los tejidos blandos circundantes y metástasis a distancia, especialmente a los pulmones"] },
      { type: "book", title: "LINFOMA DE HODGKIN", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=2e61c3f7", definicion: ["El linfoma de Hodgkin es un tipo de cáncer que afecta el sistema linfático", "Se caracteriza por la presencia de células de Reed-Sternberg, que son células anormales que se encuentran en los ganglios linfáticos", "Es una de las formas más comunes de linfoma y puede afectar a personas de cualquier edad"], caracteristicas: ["La presencia de células de Reed-Sternberg es característica del linfoma de Hodgkin", "Las células de Reed-Sternberg pueden ser binucleadas o multinucleadas y tienen un aspecto peculiar", "El linfoma de Hodgkin puede afectar cualquier parte del sistema linfático, incluyendo los ganglios linfáticos, el bazo y la médula ósea", "La enfermedad puede ser clasificada en diferentes subtipos según la presencia de ciertas características histológicas"] },
      { type: "book", title: "LINFOMA DE HODGKIN ESCLEROSIS NODULAR 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=609b03ce", definicion: ["El linfoma de Hodgkin esclerosi nodular es un tipo de linfoma de Hodgkin caracterizado por la presencia de esclerosis (endurecimiento) en los ganglios linfáticos", "Se caracteriza por la formación de nódulos de tejido cicatricial dentro de los ganglios linfáticos", "Es una de las formas más comunes de linfoma de Hodgkin y se presenta con mayor frecuencia en adultos jóvenes"], caracteristicas: ["La presencia de células de Reed-Sternberg lacunares, que son células grandes y anormales con múltiples núcleos", "La formación de nódulos de tejido cicatricial (esclerosis) dentro de los ganglios linfáticos", "La infiltración de células inflamatorias, como linfocitos y eosinófilos, en el tejido linfático", "La presencia de fibrosis (tejido cicatricial) que puede rodear y separar los nódulos de tejido linfático"] },
      { type: "book", title: "HODKING ESCLEROSIS NODULAR VARIANTE SINCITIAL40X", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=0b80454e", definicion: ["La enfermedad de Hodgkin es un tipo de linfoma que afecta el sistema inmunológico", "La variante sincitial de la esclerosis nodular es una forma rara y agresiva de la enfermedad de Hodgkin", "Se caracteriza por la presencia de células de Reed-Sternberg en un contexto de inflamación y fibrosis"], caracteristicas: ["Presencia de células de Reed-Sternberg con morfología sincicial", "Infiltrado inflamatorio mixto con linfocitos, histiocitos y eosinófilos", "Fibrosis lacunar y esclerosis nodular con formación de nódulos", "Expansión sinusal y arquitectura nodular con áreas de necrosis y hemorragia"] }
    ]
  },
  {
    week: "SEMANA 10",
    title: "Neoplasias malignas.",
    items: [
      { type: "book", title: "SEMANA 10: NEOPLASIAS MALIGNAS", date: "Publicado: 2 abr 2023" },
      { type: "book", title: "CARCINOMA DE PULMON 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=6317dffb", definicion: ["El carcinoma de pulmón es un tipo de cáncer que se origina en los pulmones", "Se desarrolla a partir de las células epiteliales que recubren los bronquios y los alvéolos pulmonares", "Es una de las causas principales de muerte por cáncer en todo el mundo"], caracteristicas: ["Células neoplásicas con núcleos irregulares y pleomórficos", "Presencia de atipia nuclear y mitosis anormales", "Formación de estructuras tumorales como adenocarcinomas, carcinomas escamosos o carcinomas de células pequeñas", "Invasión de las células tumorales en los tejidos circundantes, como el parénquima pulmonar y los vasos sanguíneos"] },
      { type: "book", title: "ADENOCARCINOMA PULMONAR 1", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=c08daa6d", definicion: ["Es un tipo de cáncer de pulmón que se origina en las células epiteliales glandulares", "Es el tipo más común de cáncer de pulmón en no fumadores y el segundo más común en fumadores", "Puede presentarse en diferentes subtipos, como el adenocarcinoma pulmonar in situ, invasivo y microinvasivo"], caracteristicas: ["Células neoplásicas que forman estructuras glandulares o acinares", "Proliferación de células con núcleos hiperkromáticos y citoplasma eosinofílico", "Presencia de mucina en las células tumorales, que puede ser demostrada mediante tinciones especiales", "Invasión de las células tumorales en el estroma pulmonar circundante, con posible formación de metástasis"] },
      { type: "book", title: "CARCINOMA GASTRICO", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=479c2163", definicion: ["El carcinoma gástrico es un tipo de cáncer que se origina en el estómago", "Se desarrolla a partir de las células epiteliales que recubren el interior del estómago", "Puede ser causado por factores genéticos, infecciones como la de Helicobacter pylori y factores dietéticos"], caracteristicas: ["Células cancerosas con núcleos irregulares y pleomorfismo nuclear", "Invasión de las células cancerosas en la pared del estómago", "Formación de estructuras glandulares anormales o crecimiento en masa", "Presencia de metástasis en ganglios linfáticos o en otros órganos"] },
      { type: "book", title: "ADENOCARCINOMA GASTRICO", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=36aff2a7", definicion: ["El adenocarcinoma gástrico es un tipo de cáncer que se origina en el revestimiento del estómago", "Se caracteriza por el crecimiento anormal de células glandulares que invaden el tejido estomacal", "Es uno de los cánceres más comunes en todo el mundo, con una mayor incidencia en países asiáticos"], caracteristicas: ["Presencia de células cancerosas con características glandulares, como la formación de glándulas anormales", "Invasión del tejido estomacal por parte de las células cancerosas, lo que puede llevar a la formación de úlceras", "Pérdida de la arquitectura glandular normal del estómago, reemplazada por un patrón desorganizado de crecimiento", "Posibilidad de metástasis a ganglios linfáticos y otros órganos, como el hígado y los pulmones"] },
      { type: "book", title: "CARCINOMA EPIDERMOIDE 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=fec9c6e4", definicion: ["El carcinoma epidermoide es un tipo de cáncer que se origina en las células epiteliales de la piel", "Se caracteriza por la proliferación anormal de células epiteliales que invaden los tejidos circundantes", "Es uno de los tipos más comunes de cáncer de piel y puede aparecer en cualquier parte del cuerpo"], caracteristicas: ["Presencia de células atípicas con núcleos hiperkromáticos y pleomórficos", "Formación de estructuras similares a islotes o cordones de células epiteliales anormales", "Invasión de las células tumorales en la dermis y posiblemente en tejidos más profundos", "Posible presencia de cuerpos de inclusión de queratina y otros cambios degenerativos en las células tumorales"] },
      { type: "book", title: "CARCINOMA EPIDERMOIDE 1", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=25e9c3f7", definicion: ["El carcinoma epidermoide es un tipo de cáncer que se origina en las células epiteliales de la piel", "Se caracteriza por la proliferación anormal de células epiteliales que invaden los tejidos circundantes", "Puede ocurrir en cualquier parte del cuerpo, pero es más común en áreas expuestas al sol como la cara, el cuello y las manos"], caracteristicas: ["Presencia de células atípicas con núcleos hiperkromáticos y pleomórficos", "Formación de estructuras epiteliales anormales como brotes y cordones", "Invasión de las células tumorales en la dermis y otros tejidos subyacentes", "Posible presencia de cuerpos de inclusión de keratina y otros cambios degenerativos"] },
      { type: "book", title: "CARCINOMA ESCAMOSO EN LENGUA", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=102af0cc", definicion: ["El carcinoma escamoso en lengua es un tipo de cáncer que se desarrolla en la lengua", "Se origina en las células escamosas que recubren la superficie de la lengua", "Es uno de los tipos más comunes de cáncer de cabeza y cuello"], caracteristicas: ["Presencia de células anaplásicas con núcleos irregulares y aumento de la relación núcleo-citoplasma", "Invasión de las células cancerosas en la estroma subyacente", "Formación de estructuras similares a islotes o cordones de células cancerosas", "Presencia de queratinización, que se manifiesta como la formación de perlitas de queratina o cuerpos de keratinización"] },
      { type: "book", title: "CARCINOMA DUCTAL DE MAMA", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=06e2fb28", definicion: ["Es el tipo más común de cáncer de mama, originándose en los conductos mamarios.", "Se caracteriza por el crecimiento anormal de células epiteliales en los ductos mamarios.", "Puede ser invasivo o no invasivo, dependiendo de si ha penetrado la pared del ducto o no."], caracteristicas: ["Células tumorales que forman estructuras ductales anormales.", "Proliferación celular desorganizada con pérdida de polaridad.", "Presencia de atipia nuclear, como núcleos grandes y pleomórficos.", "Invasión del estroma mamario circundante por parte de las células tumorales."] },
      { type: "book", title: "CARCINOMA DUCTAL 40X", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=917cceca", definicion: ["El carcinoma ductal es un tipo de cáncer que se origina en los conductos mamarios", "Se caracteriza por el crecimiento anormal de células en los conductos mamarios", "Puede ser in situ, es decir, no invasivo, o invasivo, cuando se extiende más allá de los conductos"], caracteristicas: ["Células neoplásicas que forman estructuras ductales anormales", "Proliferación celular desorganizada con pérdida de polaridad", "Presencia de atipia nuclear y citoplasmática", "Invasión del estroma mamario circundante en casos de carcinoma ductal invasivo"] }
    ]
  },
  {
    week: "SEMANA 9",
    title: "Neoplasias benignas.",
    items: [
      { type: "video", title: "VIDEO SEMANA 9: NEOPLASIAS BENIGNAS", date: "Publicado: 2 abr 2023" },
      { type: "book", title: "NEVUS INTRADERMICO", date: "Publicado: 22 may 2023" },
      { type: "book", title: "CISTOADENOMA MUCINOSO DE OVARIO", date: "Publicado: 22 may 2023" },
      { type: "book", title: "FIBROADENOMA MAMARIO", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=7a6bef85", definicion: ["Tumor benigno más común de la glándula mamaria", "Se origina en el estroma mamario y puede ser de crecimiento lento", "Puede ocurrir en cualquier edad, pero es más frecuente en mujeres jóvenes"], caracteristicas: ["Estroma celular y colágeno densamente compacto", "Glandulares y epiteliales bien definidos con arquitectura ordenada", "Proliferación de células mesenquimales y epiteliales", "Presencia de cápsula fibrosa que lo rodea y lo separa del tejido mamario circundante"] },
      { type: "book", title: "ADENOMA DE COLON 1", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=895fc764", definicion: ["El adenoma de colon es un tipo de pólipo que se desarrolla en el revestimiento del intestino grueso", "Es una lesión benigna que puede evolucionar hacia un cáncer de colon si no se trata", "Se caracteriza por un crecimiento anormal de células en la mucosa del colon"], caracteristicas: ["Presenta un patrón de crecimiento glandular con células epiteliales atípicas", "Puede tener diferentes grados de displasia, desde leve hasta severa", "La arquitectura glandular puede ser tubular, villosa o tubulovillosa", "Puede mostrar infiltración de células inflamatorias y fibrosis en la lámina propia"] },
      { type: "book", title: "ADENOMA DE COLON 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=7e78a87f", definicion: ["El adenoma de colon es un tipo de pólipo que se desarrolla en el revestimiento del intestino grueso", "Es una lesión benigna que puede evolucionar hacia un cáncer de colon si no se trata", "Se caracteriza por un crecimiento anormal de células epiteliales que forman un tumor"], caracteristicas: ["Está compuesto por células epiteliales que han sufrido una transformación neoplásica", "Presenta una arquitectura glandular irregular con células que pueden variar en tamaño y forma", "Puede mostrar displasia, que es un indicador de potencial malignidad", "La mayoría de los adenomas de colon son pediculados, es decir, están unidos al intestino por un tallo"] },
      { type: "book", title: "ADENOMA DE COLON 3", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=0b61172d", definicion: ["El adenoma de colon es un tipo de pólipo que se desarrolla en el revestimiento del intestino grueso", "Es una lesión benigna que puede evolucionar hacia un cáncer de colon si no se trata", "Se caracteriza por un crecimiento anormal de células epiteliales que forman un tumor"], caracteristicas: ["Está compuesto por células epiteliales que han sufrido una transformación neoplásica", "Presenta una arquitectura glandular irregular con células que pueden variar en tamaño y forma", "Puede mostrar displasia, que es un indicador de potencial malignidad", "Puede ser clasificado en diferentes subtipos según su grado de displasia y su arquitectura"] },
      { type: "book", title: "LEIOMIOMA 1", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=45ed22f5", definicion: ["Tumor benigno que se desarrolla en el músculo liso del útero", "Puede causar síntomas como dolor pélvico, sangrado menstrual abundante y presión sobre la vejiga", "Es una de las afecciones ginecológicas más comunes en mujeres en edad reproductiva"], caracteristicas: ["Está compuesto por células musculares lisas que se han proliferado de manera anormal", "Presenta un patrón de crecimiento bien definido, con células dispuestas en haces o fascículos", "Las células tumorales suelen ser uniformes y no presentan signos de malignidad", "Puede mostrar áreas de degeneración, como necrosis, hemorragia o calcificación, especialmente en leiomiomas grandes"] },
      { type: "book", title: "LEIOMIOMA 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=10f4c5b9", definicion: ["Tumor benigno que se desarrolla en el músculo liso del útero", "Puede causar síntomas como dolor pélvico, sangrado menstrual abundante y presión sobre la vejiga", "Es una de las afecciones ginecológicas más comunes en mujeres en edad reproductiva"], caracteristicas: ["Está compuesto por células musculares lisas que se han proliferado de manera descontrolada", "Presenta un patrón de crecimiento bien definido, con células dispuestas en haces o fascículos", "Las células tumorales suelen ser uniformes y no presentan signos de atipia o malignidad", "Puede tener diferentes tamaños y ubicaciones dentro del útero, incluyendo el miometrio y la submucosa"] }
    ]
  },
  {
    week: "SEMANA 8",
    title: "PRIMER EXAMEN PRÁCTICO",
    items: [
      { type: "info", title: "Los estudiantes verán este tema una vez que se le agregue trabajo", date: "" }
    ]
  },
  {
    week: "SEMANA 7",
    title: "REPASO DE LÁMINAS",
    items: [
      { type: "book", title: "REPASO SEGUNDA PARTE", date: "Publicado: 12 may 2023, 2 comentarios" },
      { type: "video", title: "VIDEO REPASO PRIMERA PARTE", date: "Publicado: 7 may 2023, 3 comentarios" }
    ]
  },
  {
    week: "SEMANA 6",
    title: "Inmunopatología. Rechazo de trasplantes.",
    items: [
      { type: "book", title: "GLOMERULONEFRITIS LUPICA", date: "Editado: 26 abr 2023", url: "https://pathpresenter.net/public/display?token=3d2aa6e9", definicion: ["La glomerulonefritis lúpica es una manifestación renal de la enfermedad sistémica del lupus eritematoso", "Se caracteriza por la inflamación de los glomérulos renales debido a la deposición de complejos inmunes", "Puede variar en su gravedad y presentación clínica, desde una enfermedad asintomática hasta una insuficiencia renal aguda"], caracteristicas: ["Deposición de complejos inmunes en la membrana basal glomerular y en el mesangio", "Inflamación y proliferación de las células glomerulares, incluyendo células mesangiales y podocitos", "Lesiones segmentarias o globales en los glomérulos, con posible afectación de los capilares y los túbulos renales", "Presencia de cuerpos hematoxifilinos, también conocidos como cuerpos de \"wire loop", "en la membrana basal glomerular"] },
      { type: "book", title: "GLOMERULONEFRITIS LUPICA 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=337551be", definicion: ["La glomerulonefritis lúpica es una manifestación renal de la enfermedad sistémica lupus eritematoso", "Se caracteriza por la inflamación de los glomérulos renales debido a la deposición de complejos inmunes", "Puede variar desde una forma asintomática hasta una nefritis rápidamente progresiva"], caracteristicas: ["Deposición de complejos inmunes en la membrana basal glomerular y en el mesangio", "Inflamación y proliferación de las células glomerulares, incluyendo células mesangiales y podocitos", "Lesiones glomerulares que pueden incluir proliferación endocapilar, exudados hialinos y cambios membranosos", "Presencia de cuerpos hematoxilofílicos o \"cuerpos de wire loop\" en la membrana basal glomerular"] },
      { type: "book", title: "RECHAZO RENAL CRÓNICO", date: "Editado: 2 abr 2023" },
      { type: "book", title: "SJOGREN", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=5af328c0", definicion: ["Enfermedad autoinmune crónica que afecta principalmente las glándulas salivales y lacrimales", "Se caracteriza por la inflamación y destrucción de las glándulas exocrinas, lo que lleva a síntomas de sequedad en la boca y los ojos", "Puede presentarse de forma aislada (Sjögren primario) o en asociación con otras enfermedades autoinmunes, como el lupus eritematoso sistémico o la artritis reumatoide"], caracteristicas: ["Infiltración linfocítica focal en las glándulas salivales y lacrimales, con formación de focos linfocíticos", "Destrucción de los acinos glandulares y su reemplazo por tejido conjuntivo", "Presencia de cuerpos de Russell y cuerpos de colágeno en las glándulas afectadas", "Inflamación y fibrosis en las glándulas salivales y lacrimales, lo que lleva a una disminución en la producción de saliva y lágrimas"] },
      { type: "book", title: "NEUMONIA INTERSTICIAL", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=ac3a2996", definicion: ["La neumonía intersticial es una inflamación del tejido intersticial del pulmón", "Se caracteriza por la inflamación de los espacios intersticiales del pulmón, incluyendo el tejido conectivo y el espacio alveolar", "Puede ser causada por una variedad de factores, incluyendo infecciones, enfermedades autoinmunes y exposición a toxinas"], caracteristicas: ["Infiltración de células inflamatorias en el tejido intersticial", "Fibrosis y cicatrización del tejido pulmonar", "Presencia de células gigantes y granulomas en algunos casos", "Alteraciones en la arquitectura alveolar y el intercambio gaseoso"] },
      { type: "book", title: "PENFIGO VULGAR 1", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=81215d1d", definicion: ["Enfermedad autoinmune crónica que afecta la piel y las mucosas", "Se caracteriza por la formación de ampollas y erosiones en la piel y las mucosas", "Puede ser grave y potencialmente mortal si no se trata adecuadamente"], caracteristicas: ["Presencia de acantólisis, que es la separación de las células epiteliales", "Formación de ampollas intraepiteliales y subepiteliales", "Infiltrado inflamatorio en la dermis y la epidermis", "Depósitos de inmunoglobulinas y complemento en la unión dermo-epidérmica"] },
      { type: "book", title: "PENFIGO VULGAR 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=89dea610", definicion: ["Enfermedad autoinmune crónica que afecta la piel y las mucosas", "Se caracteriza por la formación de ampollas y erosiones en la piel y las mucosas", "Puede ser grave y potencialmente mortal si no se trata adecuadamente"], caracteristicas: ["Presencia de anticuerpos contra las desmogleínas, proteínas que mantienen unidas las células epiteliales", "Ampollas intraepiteliales que se forman debido a la separación de las células epiteliales", "Infiltrado inflamatorio en la dermis y la epidermis", "Acantólisis, que es la separación y muerte de las células epiteliales debido a la acción de los anticuerpos"] }
    ]
  },
  {
    week: "SEMANA 5",
    title: "Trastornos hemodinámicos",
    items: [
      { type: "book", title: "INFARTO ESPLENICO", date: "Editado: 4 abr 2023", url: "https://pathpresenter.net/public/display?token=38e3ff65", definicion: ["El infarto esplénico se refiere a la muerte del tejido esplénico debido a una interrupción del suministro sanguíneo", "Puede ser causado por trombosis, embolia o compresión de los vasos sanguíneos que irrigan el bazo", "Es una condición médica que puede ser sintomática o asintomática, dependiendo de la extensión del daño"], caracteristicas: ["Necrosis coagulativa del tejido esplénico con pérdida de la arquitectura normal", "Infiltración de células inflamatorias, como neutrófilos y macrófagos, en el área afectada", "Presencia de hemorragias y edema en el tejido esplénico circundante", "Posible formación de una cápsula fibrosa alrededor del área infartada en etapas más avanzadas"] },
      { type: "book", title: "HEMORRAGIA PULMONAR", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=726dc325", definicion: ["La hemorragia pulmonar se refiere a la pérdida de sangre en los pulmones", "Puede ser causada por diversas condiciones, como enfermedades pulmonares, lesiones traumáticas o problemas de coagulación", "Se caracteriza por la presencia de sangre en el espacio alveolar o en los bronquios"], caracteristicas: ["Presencia de hematíes en el espacio alveolar y en los bronquios", "Inflamación y edema pulmonar asociados con la hemorragia", "Necrosis y daño tisular en áreas afectadas por la hemorragia", "Posible presencia de fibrina y otros productos de la coagulación en el tejido pulmonar"] },
      { type: "book", title: "CONG. PASIVA CRONICA HIGADO", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=dc74a6bc", definicion: ["La congestión pasiva crónica del hígado se refiere a un estado patológico caracterizado por la acumulación de sangre en el hígado debido a una circulación venosa obstructiva o insuficiente.", "Este trastorno puede ser el resultado de diversas condiciones, incluyendo insuficiencia cardíaca, trombosis venosa hepática o síndrome de Budd-Chiari.", "La congestión pasiva crónica puede llevar a daños hepáticos y alteraciones en la función hepática, lo que puede afectar la salud general del paciente."], caracteristicas: ["La característica microscópica más notable es la congestión sinusoidal, que se observa como un ensanchamiento de los sinusoides hepáticos debido a la acumulación de sangre.", "Se puede observar también una atrofia de los hepatocitos, especialmente en zonas pericentrales, debido a la falta de oxígeno y nutrientes.", "La fibrosis pericentral es común, lo que puede llevar a la formación de nódulos regenerativos y cambios arquitectónicos en el parénquima hepático.", "La presencia de hemosiderina en los hepatocitos y los macrófagos de Kupffer también es una característica común, resultado de la degradación de la hemoglobina procedente de los hematíes extravasados."] },
      { type: "book", title: "TROMBO EN ARTERIA CORONARIA", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=936e7a3a", definicion: ["Es la formación de un coágulo sanguíneo en una arteria coronaria que puede bloquear parcial o totalmente el flujo sanguíneo hacia el corazón", "Puede ser causado por la ruptura de una placa de ateroma, la inflamación de la pared arterial o la coagulación sanguínea anormal", "Es una de las principales causas de infarto de miocardio y muerte súbita cardíaca"], caracteristicas: ["La formación de un trombo blanco rico en fibrina y plaquetas que puede ser visible al microscopio", "La presencia de inflamación y daño en la pared arterial circundante", "La posible presencia de calcificaciones y depósitos de lípidos en la placa de ateroma subyacente", "La formación de un trombo rojo rico en eritrocitos y fibrina que puede ser visible en la superficie del trombo"] },
      { type: "book", title: "TROMBOSIS 1", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=fd0da31d", definicion: ["La trombosis se refiere a la formación de un coágulo sanguíneo dentro de un vaso sanguíneo", "Puede ocurrir en arterias o venas y puede ser causada por una variedad de factores", "La trombosis puede ser un evento grave y potencialmente mortal si no se trata adecuadamente"], caracteristicas: ["La trombosis se caracteriza por la presencia de un coágulo sanguíneo adherido a la pared del vaso", "Microscópicamente, el coágulo puede estar compuesto por fibrina, plaquetas y otros componentes sanguíneos", "La trombosis puede causar daño tisular debido a la obstrucción del flujo sanguíneo", "La inflamación y la necrosis pueden ser características adicionales en la trombosis, dependiendo de la ubicación y la gravedad del coágulo"] },
      { type: "book", title: "TROMBOSIS 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=2be83a97", definicion: ["La trombosis se refiere a la formación de un coágulo sanguíneo dentro de un vaso sanguíneo", "Puede ocurrir en arterias o venas y puede ser causada por una variedad de factores", "La trombosis puede ser un evento agudo o crónico y puede tener consecuencias graves si no se trata adecuadamente"], caracteristicas: ["La trombosis se caracteriza por la presencia de un coágulo sanguíneo adherido a la pared del vaso", "Microscópicamente, el coágulo puede estar compuesto por fibrina, plaquetas y eritrocitos", "La trombosis puede causar daño tisular debido a la obstrucción del flujo sanguíneo", "La inflamación y la necrosis pueden ser características adicionales en la trombosis, especialmente si el coágulo es grande o si el flujo sanguíneo está severamente comprometido"] },
      { type: "book", title: "TROMBO OREJUELA AURICULAR", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=af053a9c", definicion: ["El trombo orejuela auricular se refiere a la formación de un coágulo sanguíneo en la orejuela auricular, que es una estructura pequeña en la parte superior de la aurícula izquierda del corazón.", "Este coágulo puede ser causado por diversas condiciones, como la fibrilación auricular, la enfermedad valvular cardíaca o la cardiomiopatía.", "La formación de un trombo en la orejuela auricular puede aumentar el riesgo de accidente cerebrovascular y otras complicaciones cardiovasculares."], caracteristicas: ["Microscópicamente, el trombo orejuela auricular se caracteriza por la presencia de fibrina y eritrócitos organizados en una estructura laminada.", "El trombo puede estar compuesto por diferentes capas, incluyendo una capa externa de fibrina y una capa interna de eritrócitos y plaquetas.", "La superficie del trombo puede ser lisa o irregular, y puede haber áreas de calcificación o inflamación.", "En algunos casos, el trombo puede estar cubierto por un endotelio neoformado, lo que puede influir en su estabilidad y riesgo de embolización."] },
      { type: "book", title: "EDEMA PULMONAR 1", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=e031a2f6", definicion: ["El edema pulmonar es la acumulación anormal de líquido en los pulmones", "Se produce cuando el líquido se filtra desde los vasos sanguíneos hacia los espacios alrededor de los alvéolos pulmonares", "Puede ser causado por diversas condiciones, como insuficiencia cardíaca, altitudes elevadas o lesiones pulmonares"], caracteristicas: ["Acumulación de líquido en los espacios intersticiales y alveolares", "Infiltración de células inflamatorias en el tejido pulmonar", "Dilatación de los capilares pulmonares y aumento de la permeabilidad vascular", "Presencia de hemosiderina en los macrófagos alveolares debido a la ruptura de eritrocitos"] },
      { type: "book", title: "EDEMA PULMONAR 2", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=25bb3cc9", definicion: ["El edema pulmonar es una condición en la que hay un exceso de líquido en los pulmones", "Se caracteriza por la acumulación de líquido en los alvéolos y los espacios intersticiales de los pulmones", "Puede ser causado por diversas condiciones, como insuficiencia cardíaca, altitud, o lesiones pulmonares"], caracteristicas: ["Acumulación de líquido en los alvéolos y los espacios intersticiales de los pulmones", "Infiltración de células inflamatorias, como neutrófilos y macrófagos, en el tejido pulmonar", "Dilatación de los capilares pulmonares y aumento de la permeabilidad vascular", "Presencia de hemosiderina en los macrófagos alveolares, indicativa de hemorragia previa"] }
    ]
  },
  {
    week: "SEMANA 4",
    title: "Trastornos metabólico",
    items: [
      { type: "book", title: "TOFO URICO", date: "Editado: 26 abr 2023" },
      { type: "book", title: "CALCIFICACION PATOLOGICA", date: "Editado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=24586d70", definicion: ["La calcificación patológica se refiere a la acumulación anormal de sales de calcio en tejidos blandos", "Este proceso puede ocurrir en respuesta a daño tisular, inflamación crónica o alteraciones metabólicas", "Puede afectar diversas partes del cuerpo, incluyendo vasos sanguíneos, articulaciones y órganos internos"], caracteristicas: ["Depósitos de calcio en forma de hidroxiapatita o carbonato de calcio", "Puede observarse en tejidos como el endocardio, la válvula mitral, el riñón y el tejido conjuntivo", "La calcificación puede ser difusa o focal, y puede estar asociada con inflamación o necrosis", "Microscópicamente, se pueden observar cristales de calcio que pueden ser visibles con tinciones especiales como la tinción de Alizarina roja"] },
      { type: "book", title: "ARTERIOESCLEROSIS", date: "Editado: 3 abr 2023", url: "https://pathpresenter.net/public/display?token=ce6e7ba8", definicion: ["La arterioesclerosis es una enfermedad crónica que se caracteriza por el endurecimiento y engrosamiento de las paredes de las arterias", "Esto se debe a la acumulación de placas de ateroma, que son depósitos de grasa, colesterol y otros materiales", "La arterioesclerosis puede afectar cualquier arteria del cuerpo, pero es más común en las arterias coronarias, cerebrales y periféricas"], caracteristicas: ["La característica microscópica más notable de la arterioesclerosis es la formación de placas de ateroma en la pared de la arteria", "Estas placas están compuestas por macrófagos cargados de lípidos, células musculares lisas y una matriz de colágeno y elastina", "La placa de ateroma puede causar una reducción en el diámetro de la arteria, lo que puede llevar a una disminución del flujo sanguíneo", "La inflamación crónica y la activación de las células inmunes también juegan un papel importante en la patogénesis de la arterioesclerosis"] },
      { type: "book", title: "AMILOIDOSIS RENAL", date: "Editado: 3 abr 2023", url: "https://pathpresenter.net/public/display?token=777fbbef", definicion: ["La amiloidosis renal es una enfermedad caracterizada por la deposición de proteínas anormales llamadas amiloide en los riñones", "Estas proteínas se acumulan en los tejidos renales y pueden causar daño y disfunción renal", "La amiloidosis renal puede ser primaria, secundaria a otras enfermedades o hereditaria"], caracteristicas: ["Depósitos de amiloide en la membrana basal glomerular y en los capilares renales", "Lesiones glomerulares con engrosamiento de la membrana basal y proliferación de las células mesangiales", "Infiltración de células inflamatorias en el intersticio renal", "Fibrosis y esclerosis glomerular en etapas avanzadas de la enfermedad"] }
    ]
  },
  {
    week: "SEMANA 3",
    title: "Inflamación aguda y crónica II",
    items: [
      { type: "video", title: "VIDEO INTRODUCTORIO SEMANA 3: INFLAMACIÓN AGUDA Y CRÓNICA 2", date: "Editado: 2 abr 2023" },
      { type: "book", title: "COLECISTITIS CRONICA 1", date: "Editado: 4 abr 2023", url: "https://pathpresenter.net/public/display?token=dc913c5a", definicion: ["La colecistitis crónica es una inflamación persistente de la vesícula biliar", "Se caracteriza por episodios recurrentes de dolor abdominal y disfunción de la vesícula biliar", "Puede ser causada por cálculos biliares, infecciones o factores inflamatorios"], caracteristicas: ["Inflamación crónica de la pared de la vesícula biliar con presencia de linfocitos y macrófagos", "Fibrosis y cicatrices en la pared de la vesícula biliar", "Presencia de cálculos biliares en la mayoría de los casos", "Atrofia y metaplasia de la mucosa de la vesícula biliar"] },
      { type: "book", title: "COLECITITIS CRONICA 2", date: "Publicado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=bb2e8bf6", definicion: ["La colecistitis crónica es una inflamación persistente de la vesícula biliar", "Se caracteriza por episodios recurrentes de dolor abdominal y disfunción de la vesícula biliar", "Puede ser causada por cálculos biliares, infecciones o factores autoinmunes"], caracteristicas: ["Inflamación crónica del epitelio de la vesícula biliar con presencia de linfocitos y macrófagos", "Fibrosis y cicatrices en la pared de la vesícula biliar", "Presencia de cálculos biliares en la mayoría de los casos", "Atrofia y metaplasia del epitelio de la vesícula biliar en etapas avanzadas"] },
      { type: "book", title: "COLECISTITIS CRONICA CON COLESTEROLOSIS", date: "Publicado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=0948c37f", definicion: ["La colecistitis crónica con colesterosis es una inflamación persistente de la vesícula biliar", "Se caracteriza por la formación de depósitos de colesterol en la pared de la vesícula biliar", "Puede causar síntomas como dolor abdominal, náuseas y vómitos"], caracteristicas: ["Presencia de depósitos de colesterol en la pared de la vesícula biliar", "Inflamación crónica de la pared de la vesícula biliar con infiltración de células inflamatorias", "Fibrosis y espesamiento de la pared de la vesícula biliar", "Posible presencia de cálculos biliares"] },
      { type: "book", title: "ULCERA TIFICA", date: "Publicado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=2ad6b0e2", definicion: ["La úlcera tífica es una complicación grave de la fiebre tifoidea", "Se caracteriza por la formación de úlceras en el intestino delgado", "Puede ser causada por la bacteria Salmonella Typhi"], caracteristicas: ["La úlcera tífica presenta una lesión ovalada o redondeada en la mucosa intestinal", "La lesión puede tener un diámetro de hasta 1 cm y una profundidad que puede llegar a la muscularis mucosae", "El borde de la úlcera puede ser elevado y la base puede estar cubierta de una capa de fibrina y células inflamatorias", "La histopatología puede mostrar una infiltración de células inflamatorias, como neutrófilos y linfocitos, en la pared intestinal"] },
      { type: "book", title: "VASCULITIS", date: "Publicado: 2 abr 2023", url: "https://pathpresenter.net/public/display?token=017c9aa6", definicion: ["La vasculitis es una inflamación de los vasos sanguíneos", "Puede afectar arterias, venas o capilares", "Se caracteriza por la inflamación y daño a la pared vascular"], caracteristicas: ["Inflamación de la pared vascular con infiltración de células inflamatorias", "Daño a la pared vascular con necrosis y desintegración de la lámina basal", "Aumento de la permeabilidad vascular con extravasación de fluidos y células", "Formación de trombos y oclusión vascular en algunos casos"] },
      { type: "book", title: "PIELONEFRITIS CRONICA", date: "Editado: 4 abr 2023", url: "https://pathpresenter.net/public/display?token=9cbecd92", definicion: ["Infección bacteriana crónica del riñón", "Inflamación del parénquima renal y el sistema colector", "Puede ser causada por bacterias como Escherichia coli"], caracteristicas: ["Presencia de infiltrados inflamatorios crónicos en el riñón", "Fibrosis y cicatrices en el tejido renal", "Atrofia de los túbulos renales y glomérulos", "Presencia de cálculos renales o litiasis en algunos casos"] }
    ]
  },
  {
    week: "SEMANA 2",
    title: "Inflamación aguda y crónica I",
    items: [
      { type: "book", title: "CLASE INTRODUCTORIA LA PRACTICA 2", date: "Editado: 2 abr 2023" },
      { type: "book", title: "Tiroiditis de Hashimoto", date: "Editado: 1 abr 2023", url: "https://pathpresenter.net/public/display?token=d315912f&authuser=0", definicion: ["La tiroiditis de Hashimoto es una enfermedad autoinmune que afecta la glándula tiroides", "Se caracteriza por la inflamación de la tiroides y la destrucción de las células productoras de hormonas tiroideas", "Es la causa más común de hipotiroidismo en áreas del mundo con suficiente yodo en la dieta"], caracteristicas: ["Infiltración linfocítica en la glándula tiroides", "Destrucción de las células foliculares tiroideas", "Presencia de células gigantes y células de Hürthle", "Fibrosis y atrofia de la glándula tiroides en etapas avanzadas"] },
      { type: "book", title: "Granuloma caseoso", date: "Editado: 3 abr 2023", url: "https://pathpresenter.net/public/display?token=fac78530&authuser=0", url2: "https://pathpresenter.net/public/display?token=8dcb6c25&authuser=0", definicion: ["El granuloma caseoso es una lesión característica de la tuberculosis", "Se forma a partir de la necrosis caseosa central rodeada de células inflamatorias", "Es un hallazgo patognomónico de la infección por Mycobacterium tuberculosis"], caracteristicas: ["Necrosis caseosa central con aspecto de queso", "Rodeado de una capa de células epitelioides y células gigantes de Langhans", "Presencia de linfocitos y macrófagos en la periferia del granuloma", "Puede mostrar calcificación en estadios avanzados de la enfermedad"] },
      { type: "book", title: "Granuloma a cuerpo extraño", date: "Editado: 3 abr 2023", url: "https://pathpresenter.net/public/display?token=ffa7d0dc", definicion: ["Reacción inflamatoria crónica en respuesta a la presencia de un material extraño en el cuerpo", "Puede ser causada por una variedad de sustancias, incluyendo materiales quirúrgicos, partículas de polvo y otros objetos extraños", "Se caracteriza por la formación de un granuloma, que es un tipo de lesión inflamatoria crónica"], caracteristicas: ["Presencia de células gigantes multinucleadas que rodean el material extraño", "Infiltración de células inflamatorias, como linfocitos y macrófagos, en el sitio de la lesión", "Formación de tejido de granulación, que incluye la proliferación de fibroblastos y la deposición de colágeno", "Reacción de cuerpo extraño con presencia de histiocitos y células epitelioides que rodean el material extraño"] },
      { type: "book", title: "Absceso pulmonar agudo", date: "Publicado: 1 abr 2023", url: "https://pathpresenter.net/public/display?token=ab7d0ffd", definicion: ["El absceso pulmonar agudo es una infección bacteriana del pulmón que causa la formación de un absceso, una cavidad llena de pus.", "Se caracteriza por la presencia de necrosis y supuración en el tejido pulmonar, lo que puede llevar a síntomas como fiebre, tos y dolor en el pecho.", "Puede ser causado por una variedad de bacterias, incluyendo anaerobios y aerobios, y a menudo se asocia con condiciones subyacentes como la enfermedad pulmonar obstructiva crónica (EPOC) o la neumonía."], caracteristicas: ["La característica microscópica principal del absceso pulmonar agudo es la presencia de un área de necrosis y supuración en el tejido pulmonar, con una acumulación de neutrófilos y otros glóbulos blancos.", "Se observa la destrucción del tejido pulmonar, con la formación de una cavidad llena de pus y restos celulares.", "La pared del absceso puede estar formada por tejido granulomatoso y fibroso, con la presencia de células inflamatorias y fibroblastos.", "La microscopía electrónica puede mostrar la presencia de bacterias y otros microorganismos en el interior del absceso, lo que confirma el diagnóstico de infección bacteriana."] },
      { type: "book", title: "Apendicitis aguda", date: "Editado: 3 abr 2023", url: "https://pathpresenter.net/public/display?token=fa509f6d", definicion: ["La apendicitis aguda es una inflamación del apéndice vermiforme", "Se caracteriza por dolor abdominal, fiebre y náuseas", "Es una emergencia médica que requiere atención inmediata"], caracteristicas: ["Inflamación del apéndice con presencia de neutrófilos", "Necrosis del tejido apendicular con ulceración mucosa", "Presencia de bacterias y leucocitos en el tejido inflamado", "Edema y congestión vascular en la pared del apéndice"] }
    ]
  },
  {
    week: "SEMANA 1",
    title: "Patología celular y adaptación.",
    items: [
      { type: "book", title: "METAPLASIA ESCAMOSA EN CERVIX Y NIC 2", date: "Publicado: 13 feb 2024", url: "https://pathpresenter.net/public/display?token=ccf5ee32&authuser=0", definicion: ["La metaplasia escamosa en cervix y NIC se refiere a la transformación de las células columnares del epitelio cervical en células escamosas", "Este proceso puede ser una respuesta a la irritación crónica o a lesiones en la zona", "La metaplasia escamosa puede ser un precursor de lesiones más graves, como la displasia o el cáncer cervical"], caracteristicas: ["Presencia de células escamosas en lugar de células columnares en la zona afectada", "Células con núcleos grandes y oscuros, y citoplasma abundante", "Pérdida de la polaridad y la organización normal de las células epiteliales", "Posible presencia de inflamación crónica y fibrosis en la zona circundante"] },
      { type: "video", title: "VIDEO SEMANA 1: PATOLOGÍA CELULAR Y ADAPTACIÓN", date: "Publicado: 2 abr 2023", url: "https://www.youtube.com/watch?v=25XZ_p8MMv8&authuser=0", definicion: ["La patología celular y adaptación se refiere a los cambios en la estructura y función de las células en respuesta a lesiones o enfermedades", "Implica la capacidad de las células para adaptarse a condiciones adversas, como la hipoxia, la inflamación o la infección", "Estos cambios pueden ser reversibles o irreversibles, y pueden conducir a la restauración de la función normal o a la progresión de la enfermedad"], caracteristicas: ["Hipertrofia: aumento del tamaño de las células en respuesta a un aumento en la demanda de función", "Hiperplasia: aumento en el número de células en respuesta a una lesión o enfermedad", "Metaplasia: cambio en el tipo de células en respuesta a una lesión o enfermedad, como la transformación de células epiteliales en células conectivas", "Atrofia: disminución en el tamaño y función de las células en respuesta a una disminución en la demanda de función o a una lesión crónica"] },
      { type: "book", title: "CLASE INTRODUCTORIA DE LA PRÁCTICA 1", date: "Publicado: 1 abr 2023", url: "https://www.youtube.com/watch?v=u7jeM-gy1Nk&authuser=0", definicion: ["La práctica patológica es el estudio de la enfermedad a través de la observación de tejidos y células", "Implica el análisis de muestras biológicas para diagnosticar y entender la patogénesis de diversas afecciones", "La patología es fundamental para la medicina, ya que permite a los médicos tomar decisiones informadas sobre el tratamiento y el manejo de pacientes"], caracteristicas: ["La observación microscópica de tejidos y células es una característica clave de la práctica patológica", "El análisis de biopsias y muestras de tejido es esencial para el diagnóstico de enfermedades", "La identificación de patrones y anomalías celulares es crucial para la detección de condiciones como el cáncer", "La integración de técnicas de inmunohistoquímica y molecular en la práctica patológica ha mejorado significativamente la precisión diagnóstica"] },
      { type: "book", title: "ATROFIA TESTICULAR 1", date: "Editado: 3 abr 2023", url: "https://pathpresenter.net/public/display?token=c1c5c9b4", definicion: ["La atrofia testicular se refiere a la disminución del tamaño y la función de los testículos", "Puede ser causada por diversas condiciones, incluyendo lesiones, infecciones, enfermedades autoinmunes y factores hormonales", "La atrofia testicular puede afectar la fertilidad y la producción de hormonas sexuales en los varones"], caracteristicas: ["Disminución del diámetro de los túbulos seminíferos", "Reducción del número de espermatozoides y células de Sertoli", "Presencia de fibrosis y depósito de colágeno en el estroma testicular", "Alteraciones en la morfología de las células de Leydig, responsables de la producción de testosterona"] },
      { type: "book", title: "ATROFIA TESTICULAR 2", date: "Editado: 26 abr 2023", url: "https://pathpresenter.net/public/display?token=8e5eb3dd", definicion: ["La atrofia testicular se refiere a la disminución del tamaño y la función de los testículos", "Puede ser causada por diversas condiciones, incluyendo lesiones, infecciones, enfermedades autoinmunes y factores hormonales", "La atrofia testicular puede afectar la fertilidad y la producción de hormonas sexuales en los varones"], caracteristicas: ["Disminución del diámetro tubular y del espesor de la pared tubular", "Reducción del número de espermatozoides y de las células de Sertoli", "Presencia de fibrosis y depósito de colágeno en el estroma testicular", "Alteraciones en la arquitectura testicular, incluyendo la formación de quistes y la infiltración de células inflamatorias"] },
      { type: "book", title: "ATROFIA TESTICULAR 3", date: "Editado: 3 abr 2023", url: "https://pathpresenter.net/public/display?token=748f6bda", definicion: ["La atrofia testicular se refiere a la disminución del tamaño y la función de los testículos", "Puede ser causada por diversas condiciones, incluyendo lesiones, infecciones, enfermedades autoinmunes y factores hormonales", "La atrofia testicular puede afectar la fertilidad y la producción de hormonas sexuales en los varones"], caracteristicas: ["Disminución del diámetro de los túbulos seminíferos", "Reducción del número de espermatozoides y células de Sertoli", "Presencia de fibrosis y depósito de colágeno en el estroma testicular", "Alteraciones en la morfología de las células de Leydig, responsables de la producción de testosterona"] },
      { type: "book", title: "NECROSIS COAGULATIVA (INFARTO DE MIOCARDIO)", date: "Editado: 13 feb 2024", url: "https://pathpresenter.net/public/display?token=248bbe59", definicion: ["La necrosis coagulativa es una forma de muerte celular que se produce debido a la falta de oxígeno y nutrientes en los tejidos", "Se caracteriza por la coagulación de las proteínas celulares y la conservación de la estructura celular", "Es común en infartos de miocardio, donde la falta de flujo sanguíneo causa daño irreversible en el tejido cardíaco"], caracteristicas: ["Presencia de cardiomiocitos necróticos con citoplasma eosinofílico y núcleos picnóticos", "Infiltración de neutrófilos y macrófagos en el área de necrosis", "Depósito de fibrina y edema intersticial en el tejido cardíaco", "Pérdida de la estructura normal del miocardio, con reemplazo por tejido fibroso en etapas avanzadas"] },
      { type: "book", title: "ATROFIA ENDOMETRIAL", date: "Editado: 3 abr 2023", url: "https://pathpresenter.net/public/display?token=797344d4", definicion: ["La atrofia endometrial se refiere a la disminución del grosor y la función del endometrio, la capa mucosa que reviste el útero.", "Esta condición puede ser causada por la disminución de los niveles de estrógeno, lo que puede ocurrir durante la menopausia o debido a ciertas afecciones médicas.", "La atrofia endometrial puede provocar síntomas como sangrado uterino irregular, dolor pélvico y dispareunia."], caracteristicas: ["Disminución del grosor del endometrio, que puede ser evaluado mediante ecografía o biopsia.", "Pérdida de la arquitectura glandular normal, con glándulas pequeñas y estromas delgados.", "Disminución del número de glándulas y aumento del estroma fibroso.", "Presencia de inflamación crónica y cambios degenerativos en las células del endometrio."] },
      { type: "book", title: "METAPLASIA INTESTINAL ESOFAGO DE BARRETT", date: "Editado: 3 abr 2023", url: "https://pathpresenter.net/public/display?token=584e4e83", definicion: ["La metaplasia intestinal esofágica de Barrett es una condición en la que el revestimiento del esófago se ve reemplazado por tejido similar al del intestino", "Se caracteriza por la presencia de células columnares en lugar de las células escamosas que normalmente recubren el esófago", "Esta condición es un factor de riesgo para el desarrollo de adenocarcinoma de esófago"], caracteristicas: ["Presencia de células columnares con microvellosidades en la superficie luminal", "Disminución o ausencia de las células caliciformes y las glándulas mucosas del esófago", "Aumento de la proliferación celular y la expresión de marcadores de metaplasia intestinal", "Cambios en la arquitectura glandular y la presencia de criptas intestinales"] },
      { type: "book", title: "INFARTO PULMONAR", date: "Editado: 13 feb 2024", url: "https://pathpresenter.net/public/display?token=a6e7b009", definicion: ["El infarto pulmonar se refiere a la muerte del tejido pulmonar debido a la falta de oxígeno", "Generalmente se debe a una embolia pulmonar que bloquea el flujo sanguíneo a una parte del pulmón", "Puede ser causado por una variedad de factores, incluyendo trombosis, embolia y otras condiciones médicas"], caracteristicas: ["Necrosis coagulativa del tejido pulmonar con infiltración de neutrófilos", "Hemorragia alveolar y edema pulmonar", "Inflamación y congestión de los vasos sanguíneos pulmonares", "Posible formación de una cápsula fibrosa alrededor del área necrótica"] },
      { type: "book", title: "DISPLASIA DE CERVIX", date: "Editado: 26 abr 2023", url: "https://pathpresenter.net/public/display?token=ba7890aa", definicion: ["La displasia de cuello uterino es una condición pre-cancerosa caracterizada por cambios anormales en las células del cuello uterino", "Se considera un estado intermedio entre la salud y el cáncer, ya que puede progresar a cáncer cervical si no se trata", "La displasia de cuello uterino se diagnostica mediante una biopsia después de un resultado anormal en la prueba de Papanicolaou (Pap)"], caracteristicas: ["Alteraciones celulares como aumento de la relación núcleo/citoplasma y cambios en la forma y el tamaño de los núcleos", "Pérdida de la polaridad y la organización normal de las células en la capa epitelial", "Aumento de la mitosis y la presencia de figuras mitóticas anormales", "Invasión de las células displásicas en la capa basal y la lamina propia del cuello uterino"] }
    ]
  }
];

// Invertir el orden para que SEMANA 1 aparezca arriba
courseData.reverse();

// Exporting to be accessible via window in the browser
window.courseData = courseData;

const theoryData = [
  {
    week: "SEMANA 1",
    title: "Lesión y muerte celular",
    date: "31/03/26",
    teachers: "Dr. Walter Guitton, Dr. G. Cerrillo, Dr. W. Anicama",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "CLASE INAUGURAL",
      "Lesión celular reversible e irreversible",
      "Muerte celular: Mecanismos de lesión celular",
      "Correlación clínico-patológica: Ejemplos de lesión y muerte celular"
    ]
  },
  {
    week: "SEMANA 2",
    title: "Adaptación y acumulación celular",
    date: "07/04/26",
    teachers: "Dra. W. Quispe, Dra. D. Carayhua",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Adaptaciones del crecimiento y la diferenciación celular",
      "Acumulaciones intracelulares",
      "Calcificaciones patológicas",
      "Envejecimiento celular"
    ]
  },
  {
    week: "SEMANA 3",
    title: "Inflamación aguda",
    date: "14/04/26",
    teachers: "Dra. M. Peña, Dr. O. Reyes",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Perspectiva general de la inflamación: Definiciones y características generales",
      "Inflamación aguda"
    ]
  },
  {
    week: "SEMANA 4",
    title: "Inflamación crónica y reparación",
    date: "21/04/26",
    teachers: "Dr. D. Díaz, Dr. W. Guitton",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Inflamación crónica: Efectos sistémicos de la inflamación",
      "Reparación de tejidos"
    ]
  },
  {
    week: "SEMANA 5",
    title: "Trastornos hemodinámicos",
    date: "28/04/26",
    teachers: "Dr. J. Castillo, Dr. S. Dávila",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Edemas y derrames: Hiperemia y congestión",
      "Hemostasia, trastornos hemorrágicos y trombosis",
      "Embolia, Infarto y Shock"
    ]
  },
  {
    week: "SEMANA 6",
    title: "Inmunopatología y trasplantes",
    date: "05/05/26",
    teachers: "Dra. R. Meléndez, Dr. E. Millones",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Hipersensibilidad: Lesión tisular mediada por el sistema inmunitario",
      "Enfermedades autoinmunitarias",
      "Rechazo de trasplantes"
    ]
  },
  {
    week: "SEMANA 7",
    title: "Inmunodeficiencias y amiloidosis",
    date: "12/05/26",
    teachers: "Dr. W. Guitton, Dr. E. Millones",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Enfermedades por inmunodeficiencias",
      "Amiloidosis"
    ]
  },
  {
    week: "SEMANA 8",
    title: "I EXAMEN TEÓRICO",
    date: "19/05/26",
    teachers: "Equipo docente",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "I EXAMEN TEÓRICO"
    ]
  },
  {
    week: "SEMANA 9",
    title: "Genética y enfermedad humana",
    date: "26/05/26",
    teachers: "Dra. G. Lara, Dra. A. Asencio",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Genes y enfermedad humana",
      "Diagnóstico genético molecular"
    ]
  },
  {
    week: "SEMANA 10",
    title: "Neoplasias benignas y malignas",
    date: "02/06/26",
    teachers: "Dr. C. Barrionuevo, Dra. N. Rosas",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Neoplasia: Nomenclatura",
      "Características de las neoplasias benignas y malignas",
      "Epidemiología de los tumores malignos"
    ]
  },
  {
    week: "SEMANA 11",
    title: "Bases moleculares del cáncer",
    date: "09/06/26",
    teachers: "Dra. S. Dávila, Dra. S. Maldonado",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Bases moleculares de los tumores malignos: Función de las alteraciones genéticas y epigenéticas"
    ]
  },
  {
    week: "SEMANA 12",
    title: "Carcinogénesis y aspectos clínicos",
    date: "16/06/26",
    teachers: "Dr. J. Somocurcio, Dra. Y. Limache",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Sustancias cancerígenas y sus interacciones celulares",
      "Aspectos clínicos de las neoplasias"
    ]
  },
  {
    week: "SEMANA 13",
    title: "Patogenia microbiana",
    date: "23/07/26",
    teachers: "Dra. G. Gutiérrez, Dr. O. Reyes",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Principios generales de la patogenia microbiana",
      "Técnicas especiales para el diagnóstico de los agentes infecciosos"
    ]
  },
  {
    week: "SEMANA 14",
    title: "Patología ambiental y laboral",
    date: "30/07/26",
    teachers: "Dr. J. Castillo, Dra. G. Gutiérrez",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Riesgos profesionales para la salud: Exposición industrial y agrícola",
      "Efectos del tabaco y efectos del alcohol",
      "Lesiones por fármacos terapéuticos y drogas de abuso"
    ]
  },
  {
    week: "SEMANA 15",
    title: "Agentes físicos y nutrición",
    date: "07/07/26",
    teachers: "Dra. E. Paz, Dra. S. Maldonado",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "Daños por agentes físicos",
      "Enfermedades nutricionales"
    ]
  },
  {
    week: "SEMANA 16",
    title: "II EXAMEN TEÓRICO",
    date: "14/07/26",
    teachers: "Equipo docente",
    location: "Auditorio Pardo Figueroa / Aula de teoría Instituto",
    topics: [
      "II EXAMEN TEÓRICO"
    ]
  }
];

window.theoryData = theoryData;
